---
# Playbook to install XWiki on a Tomcat8/PostgreSQL with all its dependancies on RHEL/CentOS 7
- name: "XWiki prerequisites & configuration"
  hosts: all
#Comment this If you don't install on local machine
  connection: local
  become: yes
  vars:
    - jdk_version: java-1.8.0-openjdk.x86_64
    - xwiki_password: xwiki
    - tomcat_version: 8.5.32
    - tomcat8_path: /var/lib/tomcat8
#You can customize this if you don't want XWiki as tomcat ROOT
    - xwiki_path: ROOT
    - xwiki_version: "10.6.1"
#versions before 10.5 used to be accessible on http://download.forge.ow2.org/xwiki/xwiki-{{ xwiki_version }}.war and had various filenames format
#now, everything seems to be on nexus.xwiki.org with the same filename format
    - xwiki_artifact_url: http://nexus.xwiki.org/nexus/service/local/repo_groups/public/content/org/xwiki/platform/xwiki-platform-distribution-war/10.6.1/xwiki-platform-distribution-war-{{xwiki_version}}.war
    - jdbc_postgresql_version: 42.1.4
    - clean_tomcat_ROOT: yes
#Change if xwiki_path is not set to ROOT
    - clean_tomcat_xwiki: no
  vars_prompt:
    - name: "xwiki_password"
      prompt: "XWiki Database Password"
  roles:
    - install_xwiki
#If you have proxy issues, set this
#  environment:
#    - http_proxy: http://{{ proxy }}:8080
#    - https_proxy: https://{{ proxy }}:8080
